services:
  my-project-backend-service:
    image: 'romandanov/berkut_project:2.0'
    container_name: 'berkut-back-container'
    depends_on:
      berkut-database-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://berkut-database-service:3306/db_for_berkut_project?useUnicode=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8888:8080
    networks:
      - my-network

  berkut-database-service:
    image: 'mysql'
    container_name: 'berkut-database-container'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_for_berkut_project
    ports:
      - 2345:3306
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  my-network:
